FROM golang:1.25 AS builder

WORKDIR /app

RUN go install github.com/air-verse/air@v1.62.0

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

RUN go install github.com/a-h/templ/cmd/templ@v0.3.977

RUN go install github.com/a-h/templ/cmd/templ@latest

RUN wget -O /usr/local/bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.18/tailwindcss-linux-x64
RUN chmod +x /usr/local/bin/tailwindcss

COPY go.mod go.sum ./
RUN go mod download

RUN mkdir -p tmp
